import SectionWrapper from "./SectionWrapper";
import ScreenshotFrame from "./ScreenshotFrame";
import { Mail, Sparkles, Send, Eye } from "lucide-react";

const OutreachSection = () => (
  <>
    <SectionWrapper className="bg-[#0b0b12]">
      <div className="grid md:grid-cols-2 gap-16 items-center">
        <div className="space-y-6">
          <span className="text-primary text-sm font-bold tracking-widest uppercase">Outreach AI</span>
          <h2 className="text-4xl font-bold text-white">Email che convertono</h2>
          <p className="text-lg text-white/50 leading-relaxed">
            Ogni email è generata dall'AI sulla base del profilo completo del partner:
            servizi offerti, posizione geografica, storia delle interazioni e documenti di riferimento.
          </p>
          <div className="space-y-3">
            {[
              { icon: Sparkles, text: "Generazione AI con contesto partner completo" },
              { icon: Eye, text: "Anteprima live con dati reali del destinatario" },
              { icon: Mail, text: "Variabili dinamiche: {{company}}, {{contact}}, {{city}}" },
              { icon: Send, text: "Invio diretto via SMTP o coda batch programmata" },
            ].map(({ icon: Icon, text }) => (
              <div key={text} className="flex items-center gap-3 text-white/50">
                <Icon className="w-5 h-5 text-primary shrink-0" />
                <span>{text}</span>
              </div>
            ))}
          </div>
        </div>
        <ScreenshotFrame title="Email Workspace">
          <div className="p-6 space-y-4 min-h-[300px]">
            <div className="flex items-center gap-2 text-white/30 text-sm">
              <span className="w-2 h-2 rounded-full bg-emerald-400" /> Composing for ABC Logistics — Istanbul, TR
            </div>
            <div className="p-4 rounded-lg bg-white/5 border border-white/10 space-y-3">
              <p className="text-white/60 text-sm font-medium">Subject: Partnership Opportunity — Mediterranean Corridor</p>
              <div className="text-white/40 text-xs leading-relaxed space-y-2">
                <p>Dear Mr. Yılmaz,</p>
                <p>I noticed that ABC Logistics specializes in multimodal transport across the Mediterranean corridor, with particular expertise in...</p>
                <p className="text-primary/60 italic">— Generated by AI based on partner deep search profile —</p>
              </div>
            </div>
            <div className="flex gap-2">
              <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-xs">📎 Company Profile.pdf</span>
              <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-xs">📎 Rate Card.pdf</span>
            </div>
          </div>
        </ScreenshotFrame>
      </div>
    </SectionWrapper>
  </>
);

export default OutreachSection;
