export const crmKeys = {
  partners: {
    all: ["partners"] as const,
    filtered: (filters?: Record<string, unknown>) => ["partners", filters] as const,
    paginated: (filters?: unknown) => ["partners-paginated", filters] as const,
    byCountry: (countryCode?: string | null) => ["partners-by-country", countryCode] as const,
    globe: ["partners-globe"] as const,
    globeCountry: (code?: string | null) => ["partners-globe-country", code] as const,
    countryPartnerCounts: ["country-partner-counts"] as const,
    enrichment: (...args: unknown[]) => ["enrichment-partners", ...args] as const,
    agendaCard: (ids?: unknown) => ["agenda-card-partners", ids] as const,
    agendaList: (filters?: unknown) => ["agenda-list-partners", filters] as const,
    downloadAgenda: (filters?: unknown) => ["download-agenda-partners", filters] as const,
    picker: (...args: unknown[]) => ["picker-partners", ...args] as const,
  },
  partner: (id: string) => ["partner", id] as const,
  partnerContacts: {
    all: ["partner-contacts"] as const,
    forCampaign: (ids: string) => ["partner-contacts-for-campaign", ids] as const,
    map: (...args: unknown[]) => ["partner-contacts-map", ...args] as const,
    picker: (filters?: unknown) => ["partner-contacts-picker", filters] as const,
    pickerPartner: (filters?: unknown) => ["picker-partner-contacts", filters] as const,
  },
  socialLinks: {
    all: ["social-links"] as const,
    byPartner: (partnerId?: string | null) => ["social-links", partnerId] as const,
    batch: (ids?: unknown) => ["social-links-batch", ids] as const,
    linkedin: (filters?: unknown) => ["linkedin-links-workspace", filters] as const,
  },
  contacts: {
    all: ["contacts"] as const,
    imported: (filters?: unknown) => ["imported-contacts", filters] as const,
    paginated: (...args: unknown[]) => ["contacts-paginated", ...args] as const,
    byGroup: (...args: unknown[]) => ["contacts-by-group", ...args] as const,
    groupCounts: ["contact-group-counts"] as const,
    contactsGroupCounts: ["contacts-group-counts"] as const,
    segments: (filters?: unknown) => ["contact-segment-counts", filters] as const,
    pipeline: (filters?: unknown) => ["pipeline-contacts", filters] as const,
    holdingPattern: ["holding-pattern"] as const,
    holdingPatternList: (filters?: unknown) => ["holding-pattern-list", filters] as const,
    holdingPatternEmails: (...args: unknown[]) => ["holding-pattern-emails", ...args] as const,
    holdingMessages: (filters?: unknown) => ["holding-messages", filters] as const,
    holdingUnreadCounts: ["holding-unread-counts"] as const,
    holdingTimeline: (...args: unknown[]) => ["holding-timeline", ...args] as const,
    record: (...args: unknown[]) => ["contact-record", ...args] as const,
    recordInteractions: (...args: unknown[]) => ["record-interactions", ...args] as const,
    recordActivities: (...args: unknown[]) => ["record-activities", ...args] as const,
    groupItems: (groupType?: string, groupKey?: string) => ["contact-group-items", groupType, groupKey] as const,
    picker: (...args: unknown[]) => ["picker-contacts", ...args] as const,
    pickerOrigins: ["picker-origin-options"] as const,
    pickerCountryStats: (filters?: unknown) => ["picker-country-stats-v2", filters] as const,
    proto: {
      recentContacts: (filters?: unknown) => ["proto-recent-contacts", filters] as const,
      partnerCount: (filters?: unknown) => ["proto-partner-count", filters] as const,
      partnerContacts: (filters?: unknown) => ["proto-partner-contacts", filters] as const,
      convContacts: (filters?: unknown) => ["proto-conv-contacts", filters] as const,
    },
  },
  contactInteractions: {
    all: ["contact-interactions"] as const,
    byContact: (contactId?: string | null) => ["contact-interactions", contactId] as const,
  },
  businessCards: {
    all: ["business-cards"] as const,
    forContact: (contactId?: string | null) => ["business-card-for-contact", contactId] as const,
    matches: ["business-card-matches"] as const,
    matchesPartners: ["business-card-matches", "partners"] as const,
    matchesContacts: ["business-card-matches", "contacts"] as const,
    details: (filters?: unknown) => ["bca-details-for-list", filters] as const,
    countryCounts: ["bca-country-counts"] as const,
    campaign: (...args: unknown[]) => ["bca-campaign", ...args] as const,
  },
  prospects: {
    all: ["prospects"] as const,
    byAteco: (...args: unknown[]) => ["prospects-by-ateco", ...args] as const,
    contacts: (prospectId: string) => ["prospect-contacts", prospectId] as const,
    globalStats: ["prospect-global-stats"] as const,
    ra: {
      prospect: (id?: string) => ["ra-prospect", id] as const,
      contacts: (id?: string) => ["ra-prospect-contacts", id] as const,
      interactions: (id?: string) => ["ra-prospect-interactions", id] as const,
    },
  },
  blacklist: {
    all: ["blacklist-entries"] as const,
    stats: ["blacklist-stats"] as const,
    syncLog: ["blacklist-sync-log"] as const,
    partnerIds: ["blacklist-partner-ids"] as const,
    partner: (partnerId?: string) => ["blacklist-partner", partnerId] as const,
  },
  contactMerge: {
    duplicates: ["contact-duplicates"] as const,
    duplicateCount: ["contact-duplicate-count"] as const,
  },
  partnerStats: ["partner-stats"] as const,
} as const;
