export const systemKeys = {
  cockpit: { queue: ["cockpit-queue"] as const },
  imports: {
    logs: ["import-logs"] as const,
    log: (importLogId?: string | null) => ["import-log", importLogId] as const,
    errors: (importLogId?: string | null) => ["import-errors", importLogId] as const,
    groups: ["import-groups"] as const,
  },
  downloads: {
    jobs: ["download-jobs"] as const,
    terminalLog: (jobId: string) => ["job-terminal-log", jobId] as const,
    dataViewer: (ids: unknown) => ["job-data-viewer", ids] as const,
    failedIdsNames: (ids: unknown) => ["failed-ids-names", ids] as const,
    liveProfiles: (filters?: unknown) => ["live-profiles", filters] as const,
    maxWcaId: ["max-wca-id"] as const,
    staffJobs: (filters?: unknown) => ["staff-jobs", filters] as const,
  },
  sorting: { jobs: ["sorting-jobs"] as const },
  countryStats: ["country-stats"] as const,
  directoryCache: (countryCodes: string[], networkKeys: string[]) =>
    ["directory-cache", countryCodes, networkKeys] as const,
  directoryCacheAll: ["directory-cache"] as const,
  dbPartnersForCountries: (countryCodes: string[]) => ["db-partners-for-countries", countryCodes] as const,
  dbPartnersForCountriesAll: ["db-partners-for-countries"] as const,
  noProfileWcaIds: (countryCodes: string[]) => ["no-profile-wca-ids", countryCodes] as const,
  cacheDataByCountry: ["cache-data-by-country"] as const,
  credits: { all: ["user-credits"] as const },
  subscription: { all: ["subscription"] as const },
  operators: {
    all: ["operators"] as const,
    current: ["current-operator"] as const,
    adminCheck: ["my-operator-admin-check"] as const,
  },
  clientAssignments: { all: ["client-assignments"] as const },
  reminders: { all: ["reminders"] as const },
  networkConfigs: { all: ["network-configs"] as const },
  appSettings: { all: ["app-settings"] as const },
  tokenUsage: {
    all: ["token-usage"] as const,
    today: ["token-usage-today"] as const,
    month: ["token-usage-month"] as const,
    byFunction: (days?: number) => ["token-usage-by-function", days] as const,
    settings: ["token-usage-settings"] as const,
  },
  alertConfig: { all: ["alert-config"] as const },
  authorizedUsers: { all: ["authorized-users"] as const },
  onboarding: { completed: ["onboarding-completed"] as const, check: ["onboarding-check"] as const },
  dailyBriefing: { all: ["daily-briefing"] as const },
  system: {
    health: ["system-health"] as const,
    directory: ["system-directory"] as const,
    errorLogs: ["error-logs"] as const,
  },
  telemetry: {
    requestLogs: (filters?: unknown) => ["telemetry-request-logs", filters] as const,
    pageEvents: (filters?: unknown) => ["telemetry-page-events", filters] as const,
    aiRequests: (filters?: unknown) => ["telemetry-ai-requests", filters] as const,
  },
  timingTemplates: { all: ["timing-templates"] as const },
  sendGate: {
    rules: ["send-gate-rules"] as const,
    context: (filters?: unknown) => ["send-gate-context", filters] as const,
  },
  pendingTaskCount: ["pending-task-count"] as const,
  workspaceDocs: { all: ["workspace-documents-all"] as const },
  enrichment: {
    contacts: (filters?: unknown) => ["enrichment-contacts", filters] as const,
    emailSenders: (filters?: unknown) => ["enrichment-email-senders", filters] as const,
    cockpit: (filters?: unknown) => ["enrichment-cockpit", filters] as const,
    bca: (filters?: unknown) => ["enrichment-bca", filters] as const,
  },
  notifications: {
    list: (filters?: unknown) => ["notifications", filters] as const,
    unreadCount: ["notifications-unread-count"] as const,
  },
  rbac: {
    roles: ["rbac-roles"] as const,
    role: (roleId: string) => ["rbac-role", roleId] as const,
    permissions: ["rbac-permissions"] as const,
    rolePermissions: (roleId: string) => ["rbac-role-permissions", roleId] as const,
    userRoles: (userId?: string) => ["rbac-user-roles", userId ?? "current"] as const,
    teams: ["rbac-teams"] as const,
    team: (teamId: string) => ["rbac-team", teamId] as const,
    teamMembers: (teamId: string) => ["rbac-team-members", teamId] as const,
    hasPermission: (permissionKey: string) => ["rbac-has-permission", permissionKey] as const,
  },
  uiNavigationMap: {
    all: ["ui-navigation-map"] as const,
    enabled: ["ui-navigation-map", "enabled"] as const,
    byCategory: (category: string) => ["ui-navigation-map", category] as const,
  },
} as const;
