export const v2Keys = {
  v2: {
    settings: ["v2-settings"] as const,
    operators: ["v2-operators"] as const,
    aiMemoryStats: ["v2-ai-memory-stats"] as const,
    memoryCount: ["v2-memory-count"] as const,
    kbCount: ["v2-kb-count"] as const,
    recipientSearch: (q: string) => ["v2-recipient-search", q] as const,
    dataCounts: ["v2-data-counts"] as const,
    enrichmentCounts: ["v2-enrichment-counts"] as const,
    contacts: (filters?: unknown) => ["v2", "contacts", filters] as const,
    contact: (id?: string | null) => ["v2", "contact", id] as const,
    blacklist: ["v2", "blacklist"] as const,
    channelMessages: (direction?: string, limit?: number) =>
      ["v2", "channel-messages", direction ?? "all", limit] as const,
    businessCards: (partnerId?: string) => ["v2", "business-cards", partnerId ?? "all"] as const,
    creditBalance: ["v2", "credit-balance"] as const,
    creditTransactions: ["v2", "credit-transactions"] as const,
    campaignDrafts: (filters?: unknown) => ["v2", "campaign-drafts", filters] as const,
    kbEntries: (filters?: unknown) => ["v2", "kb-entries", filters] as const,
    workspaceDocs: (filters?: unknown) => ["v2", "workspace-docs", filters] as const,
    outreachQueue: (filters?: unknown) => ["v2", "outreach-queue", filters] as const,
    busyPartners: ["v2", "busy-partners"] as const,
    sortingRules: ["v2", "sorting-rules"] as const,
    emailDownload: (filters?: unknown) => ["v2", "email-download", filters] as const,
    emailTemplates: ["v2", "email-templates"] as const,
    authorizedUsers: ["v2", "authorized-users"] as const,
    importLogs: ["v2-import-logs"] as const,
    importLogsRecent: ["v2-import-logs-recent"] as const,
    countryStats: ["v2-country-stats"] as const,
    partners: (filters?: unknown) => ["v2", "partners", filters] as const,
    partnerFacets: (filters?: unknown) => ["v2", "partner-facets", filters] as const,
    prospects: (filters?: unknown) => ["v2", "prospects", filters] as const,
    prospectPipeline: (...args: unknown[]) => ["v2", "prospect-pipeline", ...args] as const,
    activities: (filters?: unknown) => ["v2", "activities", filters] as const,
    sortingJobs: ["v2", "sorting-jobs"] as const,
    downloadJobs: (filters?: unknown) => ["v2", "download-jobs", filters] as const,
    emailSync: (filters?: unknown) => ["v2", "email-sync", filters] as const,
    emailCampaignQueue: (filters?: unknown) => ["v2", "email-campaign-queue", filters] as const,
    dailyBriefing: ["v2", "daily-briefing"] as const,
    recentCommandPrompts: ["v2", "recent-command-prompts"] as const,
    dashboardMetrics: (filters?: unknown) => ["v2", "dashboard-metrics", filters] as const,
    agentTasks: (filters?: unknown) => ["v2", "agent-tasks", filters] as const,
    agents: (filters?: unknown) => ["v2", "agents", filters] as const,
    agentChat: (agentId?: string | null) => ["v2", "agent-chat", agentId] as const,
    cockpit: (filters?: unknown) => ["v2", "cockpit", filters] as const,
    aiLab: (filters?: unknown) => ["v2", "ai-lab", filters] as const,
    inreach: (...args: unknown[]) => ["v2", "inreach", ...args] as const,
    acquisition: (filters?: unknown) => ["v2", "acquisition", filters] as const,
    staff: (filters?: unknown) => ["v2", "staff", filters] as const,
    raScrapingJobs: (filters?: unknown) => ["v2", "ra-scraping-jobs", filters] as const,
    operativePrompts: ["v2", "operative-prompts"] as const,
    acquisitionStats: ["v2", "acquisition-stats"] as const,
    campaignStats: ["v2", "campaign-stats"] as const,
    campaignQueueItems: (draftId?: string) => ["v2", "campaign-queue-items", draftId] as const,
    campaignJobs: (batchId?: string) => ["v2", "campaign-jobs", batchId] as const,
    cockpitQueue: ["v2", "cockpit-queue"] as const,
    operationsQueue: ["v2", "operations-queue"] as const,
    emailSyncJobs: ["v2", "email-sync-jobs"] as const,
    workPlans: ["v2", "work-plans"] as const,
    unreadCounts: ["v2", "unread-counts"] as const,
    sherlockLevels: (scope: "partner" | "contact", ids: readonly string[]) =>
      ["v2", "sherlock-levels", scope, [...ids].sort().join(",")] as const,
    adminUsers: ["v2", "admin-users"] as const,
    agentDetail: (agentId: string) => ["v2", "agent-detail", agentId] as const,
    campaignQueue: (draftId?: string) => ["v2", "campaign-queue", draftId ?? "global"] as const,
    partnersInfinite: (filters?: unknown) => ["v2", "partners-infinite", filters] as const,
    partnerDetail: (partnerId?: string) => ["v2", "partner", partnerId] as const,
    dashboard: ["v2", "dashboard", "metrics"] as const,
    agentCapabilities: ["v2", "agent-capabilities"] as const,
  },
} as const;
