import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import unusedImports from "eslint-plugin-unused-imports";
import { createRequire } from "node:module";

// Le regole custom sono CJS: il progetto è "type": "module", quindi servono
// via createRequire (estensione .cjs) e non via import ESM.
const requireCjs = createRequire(import.meta.url);
const noDirectAiInvoke = requireCjs("./eslint-rules/no-direct-ai-invoke.cjs");
const noDirectBulkOp = requireCjs("./eslint-rules/no-direct-bulk-op.cjs");
const noDirectDbAccess = requireCjs("./eslint-rules/no-direct-db-access.cjs");

// Plugin locale che espone le regole di governance del progetto.
const tmwe = {
  rules: {
    "no-direct-ai-invoke": noDirectAiInvoke,
    "no-direct-bulk-op": noDirectBulkOp,
    "no-direct-db-access": noDirectDbAccess,
  },
};

export default tseslint.config(
  {
    ignores: [
      "dist",
      "build",
      "coverage",
      "node_modules",
      "archive/**",
      "public/**",
      "e2e/**",
      // Generated by @lovable.dev/mcp-js during commit hooks; lint the source
      // under src/lib/mcp instead of the generated bundle.
      "supabase/functions/mcp/index.ts",
      "src/v2/ui/pages/command/_legacy/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      "unused-imports": unusedImports,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // Explicit pin: prevents accidental downgrade if recommended preset changes.
      "react-hooks/rules-of-hooks": "error",
      // Cosmetic HMR-only rule: silenced to reduce warning noise.
      // Impatta solo hot-reload in dev; non è un bug di produzione.
      "react-refresh/only-export-components": "off",
      // Silenced: molte deps sono intenzionalmente omesse per evitare
      // re-render loop; le eccezioni sono già annotate con eslint-disable
      // dove serve. Rimane attivo `rules-of-hooks` (bug reale).
      "react-hooks/exhaustive-deps": "off",
      // Delega unused-vars a `unused-imports` che offre auto-fix per gli import.
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-imports": "warn",
      "unused-imports/no-unused-vars": [
        "warn",
        { vars: "all", varsIgnorePattern: "^_", args: "after-used", argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "no-console": "error",
      "no-var": "error",
      "prefer-const": "error",
      // `!= null` è idioma legittimo per (null||undefined); vietiamo == e != su tutto il resto.
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },
  // ── Test files override: mocks & console-based assertions are legitimate ──
  // Allow `any` and `console` in test code; production rules still enforced elsewhere.
  {
    files: [
      "src/test/**/*.{ts,tsx}",
      "src/**/*.test.{ts,tsx}",
      "src/__tests__/**/*.{ts,tsx}",
      "src/**/__tests__/**/*.{ts,tsx}",
      "supabase/functions/**/*.test.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },
  // ── Ambient .d.ts declarations: `any` is idiomatic for external module shims ──
  {
    files: ["src/**/*.d.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // ── Regole strutturali (no-restricted-syntax) — BLOCCO UNICO ──
  // ESLint applica l'ultima configurazione che matcha un file: definire
  // `no-restricted-syntax` in più blocchi sovrapposti disattivava
  // silenziosamente i selector precedenti (il ban DAL era di fatto spento).
  // Tutti i selector strutturali vivono quindi in un solo blocco.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/data/**",
      "src/integrations/**",
      "src/test/**",
      "src/**/*.test.{ts,tsx}",
      "src/**/__tests__/**",
      // Layer IO v2: è il DAL della linea v2, non un bypass.
      "src/v2/io/**",
      "src/v2/observability/supabaseTraceProxy.ts",
      // Bridge e sender ufficiali del canale multicanale.
      "src/lib/messaging/**",
      "src/lib/inbox/sendMessage.ts",
      "src/hooks/useLinkedInMessagingBridge.ts",
      "src/hooks/useWhatsAppExtensionBridge.ts",
      "src/hooks/useApproveAndDispatch.ts",
      "src/components/test-extensions/**",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.object.name='supabase'][callee.property.name='from']",
          message:
            "Direct supabase.from() is forbidden outside src/data/. Use the DAL layer instead. See src/data/README.md",
        },
        {
          selector: "CallExpression[callee.property.name='sendWhatsApp']",
          message:
            "no-direct-extension-send: usa sendWhatsAppDirect / queueWhatsAppForApproval da src/lib/messaging/whatsappSender.ts.",
        },
      ],
    },
  },
  // ── Layer enforcement: components should not import from DAL directly ──
  {
    files: ["src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "warn",
        {
          patterns: [
            {
              group: ["@/data/*"],
              message:
                "Components should not import from src/data/ directly. Use a hook instead. See docs/architecture/OVERVIEW-2026-04-14.md",
            },
          ],
        },
      ],
    },
  },
  // ── Layer enforcement: hooks should not import types from components (except ui) ──
  {
    files: ["src/hooks/**/*.{ts,tsx}"],
    ignores: ["src/hooks/use-toast.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@/components/acquisition/*",
                "@/components/cockpit/*",
                "@/components/contacts/*",
                "@/components/email/*",
                "@/components/operations/*",
                "@/components/global/*",
              ],
              message:
                "Hooks should not import from src/components/. Move shared types to src/types/. See docs/architecture/OVERVIEW-2026-04-14.md",
            },
          ],
        },
      ],
    },
  },
  // ── V2 migration guardrail: warn on v1 page imports in v2 pages ──
  {
    files: ["src/v2/ui/pages/**/*.{ts,tsx}"],
    ignores: ["src/v2/ui/pages/**/*.test.{ts,tsx}", "src/v2/ui/pages/**/__tests__/**"],
    rules: {
      "no-restricted-imports": [
        "warn",
        {
          patterns: [
            {
              group: ["@/pages/*", "@/pages/**"],
              message: "V2 pages should not import from v1 src/pages/. See docs/v2/MIGRATION_STATUS.md",
            },
            {
              group: ["@/data/*"],
              message:
                "Le pagine v2 non devono importare src/data/ direttamente: usa un hook. See docs/architecture/OVERVIEW-2026-04-14.md",
            },
          ],
        },
      ],
      // Ripetuti qui perché questo blocco ridefinisce `no-restricted-syntax`
      // per le pagine v2: senza la ripetizione i selector globali sparirebbero.
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.object.name='supabase'][callee.property.name='from']",
          message:
            "Direct supabase.from() is forbidden outside src/data/. Use the DAL layer instead. See src/data/README.md",
        },
        {
          selector: "CallExpression[callee.property.name='sendWhatsApp']",
          message:
            "no-direct-extension-send: usa sendWhatsAppDirect / queueWhatsAppForApproval da src/lib/messaging/whatsappSender.ts.",
        },
        {
          selector: "ImportExpression > Literal[value=/^@\\/pages/]",
          message: "V2 pages should not lazy-import from v1 src/pages/. See docs/v2/MIGRATION_STATUS.md",
        },
      ],
    },
  },
  // ── Layer enforcement: componenti v2 (non-pagine) non importano il DAL ──
  // ── Eccezione motivata: il layer "tools"/"lib" di Command non è UI ──
  // Sono moduli di logica (tool del planner, esecutore query) senza JSX né
  // React: l'obbligo di passare da un hook non si applica. Il divieto di
  // accesso diretto alle tabelle resta attivo su di loro (blocco globale
  // no-restricted-syntax + tmwe/no-direct-db-access).
  {
    files: ["src/v2/ui/pages/command/tools/**/*.ts", "src/v2/ui/pages/command/lib/**/*.ts"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
  {
    files: ["src/v2/ui/**/*.{ts,tsx}"],
    ignores: ["src/v2/ui/pages/**"],
    rules: {
      "no-restricted-imports": [
        "warn",
        {
          patterns: [
            {
              group: ["@/data/*"],
              message:
                "I componenti v2 non devono importare src/data/ direttamente: usa un hook. See docs/architecture/OVERVIEW-2026-04-14.md",
            },
          ],
        },
      ],
    },
  },
  // ── Governance TMWE: regole custom del repo, ora effettivamente attive ──
  // Erano presenti in eslint-rules/ ma non agganciate ad alcun blocco:
  // AI Invocation Charter R3 e il vincolo bulkOps non venivano applicati.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/test/**", "src/**/*.test.{ts,tsx}", "src/**/__tests__/**"],
    plugins: { tmwe },
    rules: {
      // Attivate come warning nel batch di aggancio: emergono 45 violazioni
      // storiche reali (36 charter R3 + 9 bulkOps) che vanno migrate a
      // invokeAi()/bulkOps prima di promuovere la regola a "error".
      // Ratchet e inventario: docs/audit/lint-gates-2026-08-02.md
      "tmwe/no-direct-ai-invoke": "warn",
      "tmwe/no-direct-bulk-op": "warn",
      // Confine dati: i bypass reali sono a zero, quindi la regola nasce
      // direttamente come "error" e impedisce che il debito si riformi.
      "tmwe/no-direct-db-access": "error",
    },
  },
  // ── public/ browser extensions: basic JS linting ──
  {
    files: ["public/**/*.js", "public/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.webextensions,
        chrome: "readonly",
      },
    },
    rules: {
      "no-var": "error",
      "prefer-const": "error",
      eqeqeq: ["error", "always"],
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  // ── Edge Function (Deno) e script Node: prima erano completamente esclusi ──
  // 149 Edge Function non venivano lintate. Regole prudenti: nessun cambio di
  // comportamento, solo rilevazione di errori reali e import morti.
  {
    files: ["supabase/functions/**/*.ts", "scripts/**/*.{ts,mjs,js}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    plugins: { "unused-imports": unusedImports },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node,
        Deno: "readonly",
        EdgeRuntime: "readonly",
      },
    },
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "unused-imports/no-unused-imports": "warn",
      "no-restricted-syntax": "off",
      // Prima passata: rilevazione, non blocco. Le Edge Function non erano
      // mai state lintate; le violazioni storiche restano visibili come
      // warning e vengono ridotte a batch (ratchet nel doc dei gate).
      // Delegato a `unused-imports` come nel resto del repo: evita il doppio
      // conteggio della stessa violazione.
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-vars": [
        "warn",
        { vars: "all", varsIgnorePattern: "^_", args: "after-used", argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-unsafe-function-type": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "no-empty": "warn",
      "no-useless-escape": "warn",
      "no-case-declarations": "warn",
      "no-control-regex": "warn",
      "no-regex-spaces": "warn",
      "no-useless-catch": "warn",
      "prefer-const": "warn",
      "no-var": "warn",
    },
  },
  {
    files: ["supabase/functions/**/*.test.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },
);
