/**
 * languageDetector.ts — Detect recipient language from country code.
 */

export function detectRecipientLanguage(countryCode: string): { language: string; confidence: number; label: string } {
  const map: Record<string, { lang: string; label: string }> = {
    IT: { lang: "Italiano", label: "Italiano" },
    DE: { lang: "Deutsch", label: "Tedesco" },
    AT: { lang: "Deutsch", label: "Tedesco" },
    FR: { lang: "Français", label: "Francese" },
    ES: { lang: "Español", label: "Spagnolo" },
    PT: { lang: "Português", label: "Portoghese" },
    BR: { lang: "Português", label: "Portoghese" },
    NL: { lang: "Nederlands", label: "Olandese" },
    PL: { lang: "Polski", label: "Polacco" },
    RO: { lang: "Română", label: "Rumeno" },
    CN: { lang: "中文", label: "Cinese" },
    JP: { lang: "日本語", label: "Giapponese" },
    KR: { lang: "한국어", label: "Coreano" },
    TH: { lang: "ไทย", label: "Thailandese" },
    RU: { lang: "Русский", label: "Russo" },
    TR: { lang: "Türkçe", label: "Turco" },
    SA: { lang: "العربية", label: "Arabo" },
    AE: { lang: "العربية", label: "Arabo" },
    IN: { lang: "English", label: "Inglese" },
    US: { lang: "English", label: "Inglese" },
    GB: { lang: "English", label: "Inglese" },
    CH: { lang: "Deutsch", label: "Tedesco" },
    BE: { lang: "Nederlands", label: "Olandese" },
    SE: { lang: "Svenska", label: "Svedese" },
    NO: { lang: "Norsk", label: "Norvegese" },
    DK: { lang: "Dansk", label: "Danese" },
    FI: { lang: "Suomi", label: "Finlandese" },
    GR: { lang: "Ελληνικά", label: "Greco" },
    VN: { lang: "Tiếng Việt", label: "Vietnamita" },
    AU: { lang: "English", label: "Inglese" },
    NZ: { lang: "English", label: "Inglese" },
    CA: { lang: "English", label: "Inglese" },
    ZA: { lang: "English", label: "Inglese" },
    SG: { lang: "English", label: "Inglese" },
    HK: { lang: "English", label: "Inglese" },
    MY: { lang: "English", label: "Inglese" },
    PH: { lang: "English", label: "Inglese" },
    ID: { lang: "English", label: "Inglese" },
    CZ: { lang: "Čeština", label: "Ceco" },
    HU: { lang: "Magyar", label: "Ungherese" },
    BG: { lang: "Български", label: "Bulgaro" },
    HR: { lang: "Hrvatski", label: "Croato" },
    RS: { lang: "Srpski", label: "Serbo" },
    SK: { lang: "Slovenčina", label: "Slovacco" },
    SI: { lang: "Slovenščina", label: "Sloveno" },
    LT: { lang: "Lietuvių", label: "Lituano" },
    LV: { lang: "Latviešu", label: "Lettone" },
    EE: { lang: "Eesti", label: "Estone" },
    UA: { lang: "Українська", label: "Ucraino" },
    IL: { lang: "עברית", label: "Ebraico" },
    EG: { lang: "العربية", label: "Arabo" },
    MX: { lang: "Español", label: "Spagnolo" },
    AR: { lang: "Español", label: "Spagnolo" },
    CL: { lang: "Español", label: "Spagnolo" },
    CO: { lang: "Español", label: "Spagnolo" },
    PE: { lang: "Español", label: "Spagnolo" },
    TW: { lang: "中文", label: "Cinese" },
  };
  const match = map[countryCode?.toUpperCase()];
  if (match) return { language: match.lang, confidence: 0.95, label: match.label };
  return { language: "English", confidence: 0.60, label: "Inglese (default)" };
}
