import type { AgentRegistryEntry } from "./types";

export const CORE_AGENTS: Record<string, AgentRegistryEntry> = {
  luca: {
    id: "luca",
    displayName: "Luca AI",
    description: "Director strategico, segretario operativo dell'Operations Center. Coordina tutti gli agenti e gestisce le richieste dell'utente.",
    coreFile: "core/luca",
    avatarIcon: "Brain",
    avatarColor: "primary",
    category: "core",
    roleInModel: "oracolo",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures"],
    criticalProcedures: [
      "doctrine/safety-guardrails",
      "doctrine/anti-hallucination",
      "doctrine/data-availability",
      "LEGGE FONDAMENTALE — Holding Pattern",
      "Dottrina Uscite",
    ],
    requiredVars: ["user_alias", "user_company", "user_sector"],
    promptSources: [
      { label: "System prompt principale", source: "core/luca", promptLabTab: "system", hint: "Prompt base con ruolo e personalità" },
      { label: "Dottrina sicurezza", source: "doctrine/safety-guardrails", promptLabTab: "doctrine" },
      { label: "Anti-allucinazione", source: "doctrine/anti-hallucination", promptLabTab: "doctrine" },
    ],
    runtime: {
      edgeFunction: "ai-assistant",
      modelDefault: "gpt-4o",
      triggers: ["Chat diretta utente", "Richieste da Operations Center", "Fallback da altri agenti"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ message: string, context?: ConversationContext, user: UserProfile }",
      output: "{ reply: string, actions?: PendingAction[], suggestions?: string[] }",
    },
  },

  "super-assistant": {
    id: "super-assistant",
    displayName: "Super Consulente",
    description: "Super Consulente Strategico per pianificazione e Daily Plan. Gestisce strategie commerciali e roadmap operativa.",
    coreFile: "core/super-assistant",
    avatarIcon: "Lightbulb",
    avatarColor: "accent",
    category: "core",
    roleInModel: "oracolo",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures"],
    criticalProcedures: [
      "doctrine/anti-hallucination",
      "doctrine/data-availability",
      "LEGGE FONDAMENTALE — Holding Pattern",
      "Dottrina Multi-Canale",
      "Progressione Relazionale",
    ],
    requiredVars: ["user_alias"],
    promptSources: [
      { label: "System prompt consulente", source: "core/super-assistant", promptLabTab: "system" },
      { label: "Dottrina multi-canale", source: "Dottrina Multi-Canale", promptLabTab: "doctrine" },
      { label: "Progressione relazionale", source: "Progressione Relazionale", promptLabTab: "doctrine" },
    ],
    runtime: {
      edgeFunction: "unified-assistant",
      modelDefault: "gpt-4o",
      triggers: ["Chat sidebar consulente", "Richiesta strategica", "Daily plan generation"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ message: string, context?: ConversationContext }",
      output: "{ reply: string, dailyPlan?: DailyPlanItem[] }",
    },
  },

  "contacts-assistant": {
    id: "contacts-assistant",
    displayName: "Assistente Contatti",
    description: "Assistente maschera contatti, opera su imported_contacts. Risponde a domande sui dati CRM con query sicure.",
    coreFile: "core/contacts-assistant",
    avatarIcon: "Users",
    avatarColor: "secondary",
    category: "core",
    roleInModel: "worker",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures"],
    criticalProcedures: [
      "procedures/ai-query-engine",
      "doctrine/data-availability",
      "procedures/lead-qualification-v2",
    ],
    requiredVars: [],
    promptSources: [
      { label: "System prompt contatti", source: "core/contacts-assistant", promptLabTab: "system" },
      { label: "Query engine", source: "procedures/ai-query-engine", promptLabTab: "procedures" },
      { label: "Lead qualification v2", source: "procedures/lead-qualification-v2", promptLabTab: "procedures" },
    ],
    runtime: {
      edgeFunction: "ai-assistant",
      modelDefault: "gpt-4o-mini",
      triggers: ["Chat nella maschera contatti", "Domande sul CRM"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: ["query-planner"],
    contract: {
      input: "{ message: string, contactContext?: ContactRow }",
      output: "{ reply: string, queryResult?: Record<string, unknown>[] }",
    },
  },

  "cockpit-assistant": {
    id: "cockpit-assistant",
    displayName: "Cockpit Command",
    description: "Command Bar del Cockpit outreach, output JSON strutturato. Gestisce invio email, WhatsApp e sequenze multicanale.",
    coreFile: "core/cockpit-assistant",
    avatarIcon: "Terminal",
    avatarColor: "primary",
    category: "core",
    roleInModel: "worker",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures"],
    criticalProcedures: [
      "doctrine/data-availability",
      "procedures/email-single",
      "procedures/whatsapp-message",
      "procedures/multi-channel-sequence",
      "procedures/post-send-checklist",
      "Dottrina Multi-Canale",
    ],
    requiredVars: [],
    promptSources: [
      { label: "System prompt cockpit", source: "core/cockpit-assistant", promptLabTab: "system" },
      { label: "Procedura email singola", source: "procedures/email-single", promptLabTab: "procedures" },
      { label: "Procedura WhatsApp", source: "procedures/whatsapp-message", promptLabTab: "procedures" },
      { label: "Sequenza multicanale", source: "procedures/multi-channel-sequence", promptLabTab: "procedures" },
    ],
    runtime: {
      edgeFunction: "ai-assistant",
      modelDefault: "gpt-4o",
      triggers: ["Command bar cockpit", "Azione outreach rapida", "Sequenza automatica"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ command: string, partnerContext?: PartnerRow }",
      output: "{ actions: CockpitAction[], preview?: string }",
    },
  },

  "email-improver": {
    id: "email-improver",
    displayName: "Email Improver",
    description: "Copywriter B2B che migliora email mantenendo voce dell'autore. Applica tecniche di persuasione e ottimizza il tono.",
    coreFile: "core/email-improver",
    avatarIcon: "Sparkles",
    avatarColor: "accent",
    category: "email",
    roleInModel: "migliora",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures"],
    criticalProcedures: [
      "procedures/email-improvement-techniques",
      "§1 Filosofia di vendita",
      "§4 Cold Outreach",
      "§10 Tono e registro",
    ],
    requiredVars: ["user_alias", "user_company", "user_tone"],
    promptSources: [
      { label: "System prompt improver", source: "core/email-improver", promptLabTab: "system" },
      { label: "Tecniche miglioramento", source: "procedures/email-improvement-techniques", promptLabTab: "procedures" },
      { label: "Filosofia vendita", source: "§1 Filosofia di vendita", promptLabTab: "doctrine" },
    ],
    runtime: {
      edgeFunction: "improve-email",
      modelDefault: "gpt-4o",
      triggers: ["Pulsante 'Migliora' su bozza email", "Auto-improve pipeline"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ draft: string, tone?: string, context?: PartnerContext }",
      output: "{ improved: string, changes: string[], score: number }",
    },
  },

  "daily-briefing": {
    id: "daily-briefing",
    displayName: "Daily Briefing",
    description: "Direttore operativo che genera briefing mattutino JSON. Riassume attività, priorità e azioni del giorno.",
    coreFile: "core/daily-briefing",
    avatarIcon: "Newspaper",
    avatarColor: "secondary",
    category: "analysis",
    roleInModel: "worker",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures"],
    criticalProcedures: [
      "LEGGE FONDAMENTALE — Holding Pattern",
      "Dottrina Workflow Gate",
    ],
    requiredVars: [],
    promptSources: [
      { label: "System prompt briefing", source: "core/daily-briefing", promptLabTab: "system" },
      { label: "Holding Pattern", source: "LEGGE FONDAMENTALE — Holding Pattern", promptLabTab: "doctrine" },
      { label: "Workflow Gate", source: "Dottrina Workflow Gate", promptLabTab: "doctrine" },
    ],
    runtime: {
      edgeFunction: "daily-briefing",
      modelDefault: "gpt-4o",
      triggers: ["Cron mattutino automatico", "Richiesta manuale briefing"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ userId: string, date: string }",
      output: "{ briefing: BriefingSection[], priorities: Priority[], actions: Action[] }",
    },
  },

  "email-classifier": {
    id: "email-classifier",
    displayName: "Email Classifier",
    description: "Classificatore risposte inbound multicanale con domain routing. Analizza email in arrivo e le assegna al flusso corretto.",
    coreFile: "core/email-classifier",
    avatarIcon: "Filter",
    avatarColor: "muted",
    category: "classifier",
    roleInModel: "classifier",
    kbCategories: ["doctrine", "system_doctrine", "sales_doctrine", "procedures", "domain_routing"],
    criticalProcedures: [
      "procedures/lead-qualification-v2",
      "Dottrina Uscite",
      "Regole smistamento per dominio",
    ],
    requiredVars: [],
    promptSources: [
      { label: "System prompt classifier", source: "core/email-classifier", promptLabTab: "system" },
      { label: "Lead qualification", source: "procedures/lead-qualification-v2", promptLabTab: "procedures" },
      { label: "Smistamento dominio", source: "Regole smistamento per dominio", promptLabTab: "doctrine" },
    ],
    runtime: {
      edgeFunction: "classify-email-response",
      modelDefault: "gpt-4o-mini",
      triggers: ["Email inbound ricevuta", "Webhook inbox", "Check-inbox manuale"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ email: InboundEmail, senderHistory?: EmailThread[] }",
      output: "{ classification: EmailClass, sentiment: string, suggestedAction: string, domain: string }",
    },
  },

  "query-planner": {
    id: "query-planner",
    displayName: "Query Planner",
    description: "Pianificatore query SELECT sicure, mai esegue. Traduce domande in linguaggio naturale in query SQL sicure.",
    coreFile: "core/query-planner",
    avatarIcon: "Database",
    avatarColor: "muted",
    category: "core",
    roleInModel: "worker",
    kbCategories: ["doctrine", "procedures"],
    criticalProcedures: ["procedures/ai-query-engine"],
    requiredVars: [],
    promptSources: [
      { label: "System prompt query", source: "core/query-planner", promptLabTab: "system" },
      { label: "AI Query Engine", source: "procedures/ai-query-engine", promptLabTab: "procedures" },
    ],
    runtime: {
      edgeFunction: "ai-assistant",
      modelDefault: "gpt-4o-mini",
      triggers: ["Domanda CRM da contacts-assistant", "Richiesta dati da cockpit"],
    },
    tools: [],
    approvalRequiredTools: [],
    dependsOn: [],
    contract: {
      input: "{ question: string, schema: TableSchema[] }",
      output: "{ sql: string, explanation: string, safe: boolean }",
    },
  },
};
