/**
 * Paese → codice ISO2 → bandiera.
 *
 * I dati arrivano misti: alcune righe hanno già il codice ("PK"), altre il
 * nome esteso ("Pakistan"). Qui normalizziamo una volta sola, per tutta la V3.
 */

const NOMI_ISO2: Record<string, string> = {
  italy: "IT",
  italia: "IT",
  india: "IN",
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  "united arab emirates": "AE",
  uae: "AE",
  china: "CN",
  "saudi arabia": "SA",
  germany: "DE",
  germania: "DE",
  mexico: "MX",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  england: "GB",
  spain: "ES",
  spagna: "ES",
  france: "FR",
  francia: "FR",
  turkey: "TR",
  turkiye: "TR",
  australia: "AU",
  thailand: "TH",
  singapore: "SG",
  argentina: "AR",
  netherlands: "NL",
  holland: "NL",
  canada: "CA",
  vietnam: "VN",
  "viet nam": "VN",
  japan: "JP",
  poland: "PL",
  brazil: "BR",
  brasil: "BR",
  switzerland: "CH",
  egypt: "EG",
  malaysia: "MY",
  peru: "PE",
  taiwan: "TW",
  belgium: "BE",
  indonesia: "ID",
  "hong kong": "HK",
  portugal: "PT",
  greece: "GR",
  romania: "RO",
  bulgaria: "BG",
  ukraine: "UA",
  russia: "RU",
  "russian federation": "RU",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  austria: "AT",
  ireland: "IE",
  czechia: "CZ",
  "czech republic": "CZ",
  hungary: "HU",
  slovenia: "SI",
  slovakia: "SK",
  croatia: "HR",
  serbia: "RS",
  israel: "IL",
  jordan: "JO",
  qatar: "QA",
  kuwait: "KW",
  oman: "OM",
  bahrain: "BH",
  lebanon: "LB",
  iraq: "IQ",
  iran: "IR",
  pakistan: "PK",
  bangladesh: "BD",
  "sri lanka": "LK",
  nepal: "NP",
  philippines: "PH",
  "south korea": "KR",
  "korea, republic of": "KR",
  "south africa": "ZA",
  nigeria: "NG",
  kenya: "KE",
  ghana: "GH",
  morocco: "MA",
  tunisia: "TN",
  algeria: "DZ",
  libya: "LY",
  chile: "CL",
  colombia: "CO",
  ecuador: "EC",
  uruguay: "UY",
  paraguay: "PY",
  panama: "PA",
  "costa rica": "CR",
  guatemala: "GT",
  "dominican republic": "DO",
  "new zealand": "NZ",
  myanmar: "MM",
  cambodia: "KH",
  kazakhstan: "KZ",
  uzbekistan: "UZ",
  azerbaijan: "AZ",
  georgia: "GE",
  cyprus: "CY",
  malta: "MT",
  luxembourg: "LU",
  estonia: "EE",
  latvia: "LV",
  lithuania: "LT",
};

/** Ritorna il codice ISO2 maiuscolo, o `null` se non riconosciuto. */
export function iso2Paese(valore: string | null | undefined): string | null {
  if (!valore) return null;
  const testo = valore.trim();
  if (!testo) return null;
  if (/^[A-Za-z]{2}$/.test(testo)) return testo.toUpperCase();
  return NOMI_ISO2[testo.toLowerCase()] ?? null;
}

/** Bandiera emoji dal codice ISO2. `null` se il paese non è riconosciuto. */
export function bandieraPaese(valore: string | null | undefined): string | null {
  const iso = iso2Paese(valore);
  if (!iso) return null;
  return String.fromCodePoint(...[...iso].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}
