// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-agents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.3.6";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_agents_default = defineTool({
  name: "list_agents",
  title: "Elenca agenti AI",
  description: "Elenca gli agenti AI configurati nel CRM (nome, ruolo, stato attivo, tools assegnati).",
  inputSchema: {
    only_active: z.boolean().optional().describe("Se true, restituisce solo gli agenti attivi."),
    limit: z.number().int().optional().describe("Numero massimo di agenti da restituire (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const cap = Math.min(Math.max(Number(limit ?? 50), 1), 200);
    let query = supabaseForUser(ctx).from("agents").select("id, name, role, avatar_emoji, is_active, assigned_tools, territory_codes").is("deleted_at", null).order("created_at", { ascending: false }).limit(cap);
    if (only_active) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { agents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.3.6";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_contacts_default = defineTool2({
  name: "search_contacts",
  title: "Cerca contatti CRM",
  description: "Cerca contatti/partner nel CRM per nome azienda o email (case-insensitive). Rispetta RLS: mostra solo i contatti visibili all'utente autenticato.",
  inputSchema: {
    query: z2.string().min(1).max(200).describe("Testo da cercare (nome azienda o email)."),
    limit: z2.number().int().optional().describe("Massimo record (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const cap = Math.min(Math.max(Number(limit ?? 20), 1), 100);
    const term = String(query).replace(/[%_]/g, (m) => `\\${m}`);
    const { data, error } = await supabaseForUser2(ctx).from("partners").select("id, company_name, email, country_code, lead_status, updated_at").is("deleted_at", null).or(`company_name.ilike.%${term}%,email.ilike.%${term}%`).order("updated_at", { ascending: false }).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zrbditqddhjkutzjycgi";
var mcp_default = defineMcp({
  name: "wca-network-navigator-mcp",
  title: "WCA Network Navigator",
  version: "0.1.0",
  instructions: "Strumenti per il CRM WCA Network Navigator. Usa `list_agents` per vedere gli agenti AI configurati e `search_contacts` per cercare partner/contatti CRM. Ogni tool opera come l'utente autenticato e rispetta RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_agents_default, search_contacts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
